name: Feature request
description: Suggest an improvement for Monocle Launcher.
body:
  - type: textarea
    id: request
    attributes:
      label: What would you like to improve?
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: How would this help your launcher or bot workflow?
